### ISSUE TITLE
Paying an invoice with an external Lightning Wallet

### ISSUE THREAD

**Issue by haarts** [lightninglabs/LSAT#15]
I really like the idea behind LSAT and I'm not sure this is the right place for questions. But here it goes.

I'm reading the authentication flow as described here: https://lsat.tech/authentication-flow. Everything is clear as day. But what if the client, at step 8, does not run an `lnd` instance? In my mind's eye, the end user is presented with a Lightning invoice (as a QR code) which he then pays with his favourite wallet. How does that payment information get back to the client?

**Comment by ellemouton** [comment]
Hi @haarts :)

So technically, the client does not need to be directly connected to lnd. It can just prompt the user for a pre-image. Then the user can go pay the invoice in which ever way they want and can present the client with the invoice from the successful payment. The client only needs to know how to construct a valid LSAT from this pre-image. 

For any future questions, please use our dedicated #lsat channel in our LND dev slack: https://lightningcommunity.slack.com/archives/C0112B0JYP2

**Comment by haarts** [comment]
Alright, that makes sense. Now I need to figure out which wallets can show the pre-image and how to get that back in my envisioned CLI app. :)

I will direct my questions to Slack, apologies for the noise.

**Comment by ellemouton** [comment]
> Now I need to figure out which wallets can show the pre-image and how to get that back in my envisioned CLI app. :)

Most wallets that I have used do actually show the pre-image or at least it is always hidden somewhere in the payment details :)

**Comment by haarts** [comment]
Excellent!

(Seems I need an invite to your Slack community?)

**Comment by ellemouton** [comment]
oh, i might have sent the wrong link. Try this one? https://lightningcommunity.slack.com/join/shared_invite/zt-1e46nmtt3-~b~dDagvgozjt_b2IHFXtg#/shared-invite/email

**Comment by ellemouton** [comment]
and then once in there, search for the #lsat channel
